---
# File: macos.yml - macOS tasks file for Sutakku

## Consul
- name: Set package facts
  set_fact:
    sutakku_consul_pkg: "consul_{{ sutakku_consul_version }}_darwin_amd64.zip"

- name: Check Consul package checksum file
  become: no
  connection: local
  stat:
    path: "{{ role_path }}/files/consul_{{ sutakku_consul_version }}_SHA256SUMS"
  run_once: true
  register: consul_checksum

- name: Get consul package checksum file
  become: no
  connection: local
  get_url:
    url: "{{ sutakku_consul_checksum_file_url }}"
    dest: "{{ role_path }}/files/consul_{{ sutakku_consul_version }}_SHA256SUMS"
  run_once: true
  tags: installation
  when: consul_checksum.stat.exists == False

- name: Get Consul package checksum
  become: no
  connection: local
  shell: "grep {{ sutakku_consul_pkg }} {{ role_path }}/files/consul_{{ sutakku_consul_version }}_SHA256SUMS"
  run_once: true
  register: sutakku_consul_sha256
  tags: installation

- name: Check Consul package file
  become: no
  connection: local
  stat:
    path: "{{ role_path }}/files/{{ sutakku_consul_pkg }}"
  run_once: true
  register: consul_package

- name: Download Consul
  become: no
  connection: local
  get_url:
    url: "{{ sutakku_consul_macos_zip_url }}"
    dest: "{{ role_path }}/files/{{ sutakku_consul_pkg }}"
    checksum: "sha256:{{ sutakku_consul_sha256.stdout.split(' ')|first }}"
    timeout: 42
  run_once: true
  tags: installation
  when: consul_package.stat.exists == False

- name: Unarchive Consul
  become: no
  connection: local
  unarchive:
    src: "{{ role_path }}/files/{{ sutakku_consul_pkg }}"
    dest: "{{ sutakku_bin_path }}/"
  run_once: true
  tags: installation

## Nomad
- name: Set Nomad package
  set_fact:
    sutakku_nomad_pkg: "nomad_{{ sutakku_nomad_version }}_darwin_amd64.zip"

- name: Check Nomad package checksum file
  become: no
  connection: local
  stat:
    path: "{{ role_path }}/files/nomad_{{ sutakku_nomad_version }}_SHA256SUMS"
  run_once: true
  register: nomad_checksum

- name: Get Nomad package checksum file
  become: no
  connection: local
  get_url:
    url: "{{ sutakku_nomad_checksum_file_url }}"
    dest: "{{ role_path }}/files/nomad_{{ sutakku_nomad_version }}_SHA256SUMS"
  run_once: true
  tags: installation
  when: nomad_checksum.stat.exists == False

- name: Get Nomad package checksum
  become: no
  connection: local
  shell: "grep {{ sutakku_nomad_pkg }} {{ role_path }}/files/nomad_{{ sutakku_nomad_version }}_SHA256SUMS"
  run_once: true
  register: sutakku_nomad_sha256
  tags: installation

- name: Check Nomad package file
  become: no
  connection: local
  stat:
    path: "{{ role_path }}/files/{{ sutakku_nomad_pkg }}"
  run_once: true
  register: nomad_package

- name: Download Nomad
  become: no
  connection: local
  get_url:
    url: "{{ sutakku_nomad_macos_zip_url }}"
    dest: "{{ role_path }}/files/{{ sutakku_nomad_pkg }}"
    checksum: "sha256:{{ sutakku_nomad_sha256.stdout.split(' ')|first }}"
    timeout: 42
  run_once: true
  tags: installation
  when: consul_package.stat.exists == False

- name: Unarchive Nomad
  become: no
  connection: local
  unarchive:
    src: "{{ role_path }}/files/{{ sutakku_nomad_pkg }}"
    dest: "{{ sutakku_bin_path }}/"
  run_once: true
  tags: installation

## Vault
- name: Set Vault package
  set_fact:
    sutakku_vault_pkg: "vault_{{ sutakku_vault_version }}_darwin_amd64.zip"

- name: Get Vault package checksum file
  become: no
  connection: local
  get_url:
    url: "{{ sutakku_vault_checksum_file_url }}"
    dest: "{{ role_path }}/files/vault_{{ sutakku_vault_version }}_SHA256SUMS"
  run_once: true
  tags: installation

- name: Get Vault package checksum
  become: no
  connection: local
  shell: "grep {{ sutakku_vault_pkg }} {{ role_path }}/files/vault_{{ sutakku_vault_version }}_SHA256SUMS"
  run_once: true
  register: sutakku_vault_sha256
  tags: installation

- name: Download Vault
  become: no
  connection: local
  get_url:
    url: "{{ sutakku_vault_macos_zip_url }}"
    dest: "{{ role_path }}/files/{{ sutakku_vault_pkg }}"
    checksum: "sha256:{{ sutakku_vault_sha256.stdout.split(' ')|first }}"
    timeout: 42
  run_once: true
  tags: installation

- name: Unarchive Vault
  become: no
  connection: local
  unarchive:
    src: "{{ role_path }}/files/{{ sutakku_vault_pkg }}"
    dest: "{{ sutakku_bin_path }}/"
  run_once: true
  tags: installation

# Consul Template
- name: Set package facts
  set_fact:
    sutakku_consul_template_pkg: "consul-template_{{ sutakku_consul_template_version }}_darwin_amd64.zip"

- name: Check Consul Template package checksum file
  become: no
  connection: local
  stat: 
    path: "{{ role_path }}/files/consul-template_{{ sutakku_consul_template_version }}_SHA256SUMS"
  run_once: true
  register: consul_template_checksum

- name: Get Consul Template package checksum file
  become: no
  connection: local
  get_url:
    url: "{{ sutakku_consul_template_checksum_file_url }}"
    dest: "{{ role_path }}/files/consul-template_{{ sutakku_consul_template_version }}_SHA256SUMS"
  run_once: true
  tags: installation
  when: consul_template_checksum.stat.exists == False

- name: Get Consul Template package checksum
  become: no
  connection: local
  shell: "grep {{ sutakku_consul_template_pkg }} {{ role_path }}/files/consul-template_{{ sutakku_consul_template_version }}_SHA256SUMS"
  run_once: true
  register: sutakku_consul_template_sha256
  tags: installation

- name: Check Consul Template package file
  become: no
  connection: local
  stat:
    path: "{{ role_path }}/files/{{ sutakku_consul_template_pkg }}"
  run_once: true
  register: consul_template_package

- name: Download Consul Template
  become: no
  connection: local
  get_url:
    url: "{{ sutakku_consul_template_macos_zip_url }}"
    dest: "{{ role_path }}/files/{{ sutakku_consul_template_pkg }}"
    checksum: "sha256:{{ sutakku_consul_template_sha256.stdout.split(' ')|first }}"
    timeout: 42
  run_once: true
  when: ansible_distribution  == "MacOSX"
  tags: installation
  when: consul_template_package.stat.exists == False

- name: Unarchive Consul Template
  become: no
  connection: local
  unarchive:
    src: "{{ role_path }}/files/{{ sutakku_consul_template_pkg }}"
    dest: "{{ sutakku_bin_path }}/"
  run_once: true
  when: ansible_distribution  == "MacOSX"
  tags: installation

# envconsul
- name: Set package facts
  set_fact:
    sutakku_envconsul_pkg: "envconsul_{{ sutakku_envconsul_version }}_darwin_amd64.zip"

- name: Check envconsul package checksum file
  become: no
  connection: local
  stat:
    path: "{{ role_path }}/files/envconsul_{{ sutakku_envconsul_version }}_SHA256SUMS"
  run_once: true
  register: envconsul_checksum

- name: Get envconsul package checksum file
  become: no
  connection: local
  get_url:
    url: "{{ sutakku_envconsul_checksum_file_url }}"
    dest: "{{ role_path }}/files/envconsul_{{ sutakku_envconsul_version }}_SHA256SUMS"
  run_once: true
  tags: installation
  when: envconsul_checksum.stat.exists == False

- name: Get envconsul package checksum
  become: no
  connection: local
  shell: "grep {{ sutakku_envconsul_pkg }} {{ role_path }}/files/envconsul_{{ sutakku_envconsul_version }}_SHA256SUMS"
  run_once: true
  register: sutakku_envconsul_sha256
  tags: installation

- name: Check envconsul package file
  become: no
  connection: local
  stat:
    path: "{{ role_path }}/files/{{ sutakku_envconsul_pkg }}"
  run_once: true
  register: envconsul_package

- name: Download envconsul
  become: no
  connection: local
  get_url:
    url: "{{ sutakku_envconsul_macos_zip_url }}"
    dest: "{{ role_path }}/files/{{ sutakku_envconsul_pkg }}"
    checksum: "sha256:{{ sutakku_envconsul_sha256.stdout.split(' ')|first }}"
    timeout: 42
  run_once: true
  tags: installation
  when: envconsul_package.stat.exists == False

- name: Unarchive envconsul
  become: no
  connection: local
  unarchive: "src={{ role_path }}/files/{{ sutakku_envconsul_pkg }} dest={{ sutakku_bin_path }}/"
  run_once: true
  tags: installation
