---
# File: main.yml - main tasks file for Sutakku

- include: linux.yml
  when: ansible_distribution  == "Debian" or ansible_distribution  == "RedHat"

- include: macos.yml
  when: ansible_distribution  == "MacOSX"

- include: devtools.yml
  when: sutakku_devtools == "True"

#- block:

  #- name: Zip file cleanup
  #  become: no
  #  connection: local
  #  file: "path={{ item }} state=absent"
  #  with_fileglob: "{{ role_path }}/files/*.zip"
  #  run_once: true
  #  tags: installation
#
  #- name: SHA file cleanup
  #  become: no
  #  connection: local
  #  file: "path={{ item }} state=absent"
  #  with_fileglob: "{{ role_path }}/files/*_SHA256SUMS"
  #  run_once: true
  #  tags: installation
